---
- name: generate_locale
  ansible.builtin.command: locale-gen
  changed_when: false
  become: true

- name: restart_sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
